name: Ubuntu-Focal

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 5 * * *'

jobs:
  ci:
    name: Ubuntu-Focal
    runs-on: ubuntu-latest
    steps:
      - name: Prepare workspace
        run: |
          mkdir src

      - uses: actions/checkout@v1
        with:
          path: src

      - name: Install dependencies
        run: |
          apt update && apt upgrade
          apt install -q clang-tidy python3-vcstool python3-colcon-common-extensions python3-rosdep
          rosdep init
          rosdep update
          vcs import --input "${{ github.workspace }}/src/${{ github.event.repository.name }}/dependencies.repos" src
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build
        run: |
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DENABLE_CLANG_TIDY=ON

      - name: Test
        run: |
          colcon test
